### ISSUE TITLE
Can not unpack Realme payload.bin

### ISSUE THREAD

**Issue by SantaSpeen** [crazystylus/otadump#12]
OTA Pack: https://download.c.realme.com/flash/DP1_Android_13/EU/RMX3301_ROLL_BACK_Android12_EU.zip
Log in `log.txt` file: [log.txt](https://github.com/crazystylus/otadump/files/11293050/log.txt)

**Comment by SantaSpeen** [comment]
Other OTA pack: https://4pda.to/stat/go?u=https%3A%2F%2Fgauss-componentotacostmanual-sg.allawnofs.com%2Fremove-50de228b70e0745b42c44616f2b80d8e%2Fcomponent-ota%2F23%2F03%2F18%2F6c94e37ba4954687894199de37bcb6f4.zip&e=122319104
Log: [log.txt](https://github.com/crazystylus/otadump/files/11294682/log.txt)

**Comment by ajeetdsouza** [comment]
Fixed, thanks for pointing this out!

**Comment by crazystylus** [comment]
Hi @SantaSpeen  ,
This has been fixed in the latest release which you can find here: https://github.com/crazystylus/otadump/releases/tag/0.1.2
