### ISSUE TITLE
Build under Android OS

### ISSUE THREAD

**Issue by blackeangel** [crazystylus/otadump#21]
Hi! Please add build under Android manual or compile static binary files armv7 and arm64

**Comment by crazystylus** [comment]
Now GNU has been replaced with MUSL for static builds. Next release will have static binaries for `x86_64`, `aarch64`/`arm64`, `arm`/`armv6` and `armv7`.

If you don't want to wait for next release, you can consume build artifacts from this run which are available at the bottom of this page: https://github.com/crazystylus/otadump/actions/runs/5371287185/jobs/9743972053

**Comment by blackeangel** [comment]
> Now GNU has been replaced with MUSL for static builds. Next release will have static binaries for `x86_64`, `aarch64`/`arm64`, `arm`/`armv6` and `armv7`.
> 
> If you don't want to wait for next release, you can consume build artifacts from this run which are available at the bottom of this page: https://github.com/crazystylus/otadump/actions/runs/5371287185/jobs/9743972053

It's great :) Thank you! But I'll wait for the official release
