### ISSUE TITLE
Cannot unpack some Nokia firmware

### ISSUE THREAD

**Issue by OneNormalUsername** [crazystylus/otadump#25]
Trying to use `otadump` against the following zip https://android.googleapis.com/packages/ota-api/package/cbce4b4611f7a10bc02ee2e03872b2f4aa241b9a.zip leads to the below.

```
$ otadump cbce4b4611f7a10bc02ee2e03872b2f4aa241b9a.zip
Error: failed to parse payload

Caused by:
    Parsing requires 2394469530116587966 bytes/chars
```

`otadump` version is 0.1.2, and I have reproduced this on two different machines running Ubuntu 22.04.2 LTS (one Desktop variant, and one Server variant).

As the SHA-1 hash of the file matches its name (similarly to other OTA files hosted on android.googleapis.com/* ), I do not believe it is due to a download issue.

```
~$ sha1sum cbce4b4611f7a10bc02ee2e03872b2f4aa241b9a.zip
cbce4b4611f7a10bc02ee2e03872b2f4aa241b9a  cbce4b4611f7a10bc02ee2e03872b2f4aa241b9a.zip
```

**Comment by ajeetdsouza** [comment]
You need to extract the `payload.bin` file and run `otadump` on that.

I think this could be a common mistake, we should either add a warning, or the ability to extract directly from zip files.

**Comment by OneNormalUsername** [comment]
Oops
Sorry, it indeed works fine with the extracted payload.bin 😅
