### ISSUE TITLE
Error: failed to parse payload

### ISSUE THREAD

**Issue by Hot12345** [crazystylus/otadump#32]
Im using Windows 10 CMD. No python installed.

Getting a error message: 
when:
otadump.exe payload.bin

Error: failed to parse payload

Caused by:
    Parsing requires 4 bytes/chars
![image](https://github.com/crazystylus/otadump/assets/29144713/079c6c55-4fbe-4cfc-ba0e-0951910d33a2)

**Comment by ajeetdsouza** [comment]
Looks like your payload file is corrupted - what is the file size of `payload.bin`?

Is it possible to link the payload file here?

**Comment by crazystylus** [comment]
Closing stale issue
