### ISSUE TITLE
Add an argument to exclude an image

### ISSUE THREAD

**Issue by magi44ken** [crazystylus/otadump#33]
Hi

Is it possible to add an argument or option to exclude an image from extraction?

For example, often times we only to extract the boot.img, init_boot.img, dtao.img and other small images and don't need to extract the product.img (2.5GB file size). This will save lots of extraction time.

**Comment by crazystylus** [comment]
Hi @magi44ken ,
You can instead choose which partitions to extract by passing them to the `otadump`. Please check the example shared below.

Example
```shell
./otadump.exe ./payload.bin --partitions vbmeta_system,modem,boot
```

**Comment by crazystylus** [comment]
Closing issue as this is already supported by the cli
