### ISSUE TITLE
Newer update_metadata.proto

### ISSUE THREAD

**Issue by Arcitec** [crazystylus/otadump#35]
I just finished reading through your source-code, which is surprisingly compact and easily readable.

You've done an awesome job with this project. Thank you for creating it and sharing it!

I saw that there's a `update_metadata.proto` which contains the Protobuf spec for the payload.bin file, so out of curiosity I checked the upstream and saw that they have done some changes since this project was created.

It talks about new fields for compression and copy-on-write (cow) v3. Are those changes relevant for this project?

https://android.googlesource.com/platform/system/update_engine/+log/HEAD/update_metadata.proto

**Comment by ajeetdsouza** [comment]
> I just finished reading through your source-code, which is surprisingly compact and easily readable.

Thank you!

> It talks about new fields for compression and copy-on-write (cow) v3. Are those changes relevant for this project?

Not really. Protobuf changes should be backward compatible, so unless there's a new feature that is required to extract an OTA, we can ignore updates to that file.
