### ISSUE TITLE
Fedora build dependencies

### ISSUE THREAD

**Issue by Arcitec** [crazystylus/otadump#36]
I just want to let you know that on Fedora, the build dependencies are installable with:

```
sudo dnf install xz xz-devel protobuf-compiler pkg-config
```

Just mentioning this in case you want to add that to the readme.

However, I had to edit `Cargo.toml` to delete the "static" attribute since your patch to `rust-lzma` for Static building does not work on Fedora. It gives error that it's unable to find the library:

```
error: could not find native static library `lzma`, perhaps an -L flag is missing?

error: could not compile `rust-lzma` (lib) due to 1 previous error
```

I changed the `rust-lzma` line to:

`rust-lzma = "0.6.0"`

Now it builds. :)

Upstream bug report: https://github.com/fpgaminer/rust-lzma/issues/30

**Comment by ajeetdsouza** [comment]
Replied on the linked issue - this is not a bug.
