### ISSUE TITLE
Sourcecopy Errors / Doesn't Unpack Payload Correctly ...

### ISSUE THREAD

**Issue by class5vapor** [crazystylus/otadump#40]
I have a copy/paste of the long list of errors ... mainly stuff like this 

<unnamed>
thread '' panicked at ':thread 'src\cmd.rs
thread 'error running operation: unimplemented operation: SourceCopy::', <unnamed>' panicked at 'src\cmd.rsthread '107thread 'thread '' panicked at 'thread '<unnamed>error running operation: unimplemented operation: SourceCopy30<unnamed>:thread '<unnamed>src\cmd.rs30107', ' panicked at 'error running operation: unimplemented operation: SourceCopy:<unnamed>:<unnamed><unnamed>error running operation: unimplemented operation: SourceCopy<unnamed>' panicked at '',
' panicked at '107<unnamed>' panicked at '::src\cmd.rserror running operation: unimplemented operation: SourceCopy', 107' panicked at '30' panicked at '' panicked at '', ' panicked at 'error running operation: unimplemented operation: SourceCopysrc\cmd.rs
error running operation: unimplemented operation: SourceCopythread ':' panicked at 'error running operation: unimplemented operation: SourceCopy10730:', src\cmd.rs:error running operation: unimplemented operation: SourceCopy
error running operation: unimplemented operation: SourceCopyerror running operation: unimplemented operation: SourceCopysrc\cmd.rserror running operation: unimplemented operation: SourceCopy:thread '', <unnamed>30error running operation: unimplemented operation: SourceCopy', :
107src\cmd.rs:30', ', ', thread '', :', src\cmd.rs<unnamed>107' panicked at '
', src\cmd.rs30thread '::107
src\cmd.rssrc\cmd.rssrc\cmd.rs<unnamed>src\cmd.rs107src\cmd.rs:' panicked at ':error running operation: unimplemented operation: SourceCopysrc\cmd.rs:
<unnamed>30107thread '::' panicked at '::::107thread 'error running operation: unimplemented operation: SourceCopy30', :107:' panicked at 'thread '
:<unnamed>107107error running operation: unimplemented operation: SourceCopy10710730107:<unnamed>',
:107src\cmd.rs30error running operation: unimplemented operation: SourceCopy<unnamed>thread '30' panicked at '::', :30
:30' panicked at ':30src\cmd.rs:
', ' panicked at '<unnamed>
error running operation: unimplemented operation: SourceCopy:30src\cmd.rs30
thread '30thread '
:30
src\cmd.rs107' panicked at 'error running operation: unimplemented operation: SourceCopyerror running operation: unimplemented operation: SourceCopythread 'thread '', 30
:

I can post or send the whole thing ... not sure what those errors are

Running Win11 (64-bit), 13th Gen Intel(R) Core(TM) i7-13700H   1.70 GHz Processor, 32GB RAM

Can anyone help me with this?
Pls and Thanks...maybe I'm missing other dependencies etc...

=]

**Comment by ajeetdsouza** [comment]
Could you upload the payload file here?

**Comment by class5vapor** [comment]
payload.bin
<https://drive.google.com/file/d/1Y2GWbTlvjyc4ws-7QFnZugmFTkksgBYl/view?usp=drive_web>
Sure thing sir, here you go.

=]

**Comment by class5vapor** [comment]
let me know if you need / want the zip file ... my phone's a oneplus 11 5G,
I'm in Canada, and I get the OTA update from the oneplus update app, it
allows me to download it.
So, to-me, from them it must be fine...but as I say perhaps I'm missing
something in my environment to be able to unpack it correctly, it DOES do
some of the files seemingly fine...but the one I need, boot_init.img ... it
doesn't seem to be good.

=]

**Comment by class5vapor** [comment]
I think I see my error, the file I supplied and tested this on was not the
full otaupdate file, it was the incremental one...because I just downloaded
the FULL ota file and used otadumper and it seems to work fine...
I apologize...

it just confused me because the incremental vs the full ota update have two
similar but actually different numbers ... and my phone lists the
incremental version number in the about--> version tab and NOT the full
one's exact version number.
I'm not 100% sure if extracting the init_boot file from the full one and
using it to patch with Magisk to root the phone...I'm hesitant since it IS
technically a different number there...
from what I'm flashing the wrong thing to my boot_init could bootloop me
and then I'll be in some trouble...like I need to 100% make SURE I know if
the boot_init I extracted from this OTA update is gonna work to get me
outta a jam if indeed I try to root and get bootlooped...otherwise I could
brick the phone...

not sure who I could ask about why there are different version numbers for
the incremental / full versions ... or if you know if they're the "same"
thing really

=]

As for your tool ... again it's my mistake .. it does seem to work

=]

and thanks for making this tool!!

=]

**Comment by ajeetdsouza** [comment]
No problem!
